const express = require("express");
const { sendResponse } = require("../utils/common");
require("dotenv").config();
const locationController = express.Router();
require("dotenv").config();
const cloudinary = require("../utils/cloudinary");
const upload = require("../utils/multer");

// const City = [
//   "Agartala",
//   "Agra",
//   "Ahmedabad",
//   "Aizawl",
//   "Ajmer",
//   "Alappuzha",
//   "Aligarh",
//   "Allahabad",
//   "Ambala",
//   "Amravati",
//   "Amritsar",
//   "Anantapur",
//   "Aurangabad",
//   "Bangalore",
//   "Bareilly",
//   "Belgaum",
//   "Bhagalpur",
//   "Bharatpur",
//   "Bhilai",
//   "Bhiwandi",
//   "Bhopal",
//   "Bhubaneswar",
//   "Bikaner",
//   "Bilaspur",
//   "Bokaro Steel City",
//   "Chandigarh",
//   "Chennai",
//   "Coimbatore",
//   "Cuttack",
//   "Dehradun",
//   "Delhi",
//   "Dhanbad",
//   "Durgapur",
//   "Erode",
//   "Faridabad",
//   "Firozabad",
//   "Ghaziabad",
//   "Gorakhpur",
//   "Gulbarga",
//   "Guntur",
//   "Gurgaon",
//   "Guwahati",
//   "Gwalior",
//   "Hubli",
//   "Hyderabad",
//   "Imphal",
//   "Indore",
//   "Jabalpur",
//   "Jaipur",
//   "Jalandhar",
//   "Jammu",
//   "Jamnagar",
//   "Jamshedpur",
//   "Jhansi",
//   "Jodhpur",
//   "Kannur",
//   "Kanpur",
//   "Karnal",
//   "Kochi",
//   "Kolkata",
//   "Kollam",
//   "Kozhikode",
//   "Kurnool",
//   "Latur",
//   "Lucknow",
//   "Ludhiana",
//   "Madurai",
//   "Malappuram",
//   "Mathura",
//   "Meerut",
//   "Moradabad",
//   "Mumbai",
//   "Mysore",
//   "Nagpur",
//   "Nanded",
//   "Nashik",
//   "Nellore",
//   "Noida",
//   "Patna",
//   "Pondicherry",
//   "Prayagraj",
//   "Pune",
//   "Raipur",
//   "Rajahmundry",
//   "Rajkot",
//   "Ranchi",
//   "Rourkela",
//   "Salem",
//   "Sangli",
//   "Shimla",
//   "Siliguri",
//   "Solapur",
//   "Srinagar",
//   "Surat",
//   "Thanjavur",
//   "Thiruvananthapuram",
//   "Tiruchirappalli",
//   "Tiruppur",
//   "Udaipur",
//   "Ujjain",
//   "Vadodara",
//   "Varanasi",
//   "Vasai-Virar",
//   "Vijayawada",
//   "Visakhapatnam",
//   "Warangal",
//   "Yamunanagar",
//   "Ahmednagar",
//   "Ajmer",
//   "Akola",
//   "Aligarh",
//   "Alwar",
//   "Amroha",
//   "Anand",
//   "Arrah",
//   "Asansol",
//   "Bahraich",
//   "Ballari",
//   "Begusarai",
//   "Bhagalpur",
//   "Bharuch",
//   "Bhavnagar",
//   "Bhiwani",
//   "Bidar",
//   "Bulandshahr",
//   "Chhapra",
//   "Davanagere",
//   "Dhule",
//   "Dibrugarh",
//   "Dimapur",
//   "Etawah",
//   "Farrukhabad",
//   "Fatehpur",
//   "Firozpur",
//   "Gandhinagar",
//   "Gaya",
//   "Ghazipur",
//   "Godhra",
//   "Gopalpur",
//   "Gulbarga",
//   "Hajipur",
//   "Haldwani",
//   "Hisar",
//   "Hoshangabad",
//   "Idukki",
//   "Jabalpur",
//   "Jagdalpur",
//   "Jalgaon",
//   "Jalna",
//   "Jalpaiguri",
//   "Jammu",
//   "Jamnagar",
//   "Jamshedpur",
//   "Jhansi",
//   "Jodhpur",
//   "Junagadh",
//   "Kadapa",
//   "Kakinada",
//   "Kalyan-Dombivli",
//   "Kamarhati",
//   "Kancheepuram",
//   "Karaikudi",
//   "Karimnagar",
//   "Karnal",
//   "Karur",
//   "Katni",
//   "Kavali",
//   "Kishanganj",
//   "Kolhapur",
//   "Kollam",
//   "Kota",
//   "Kottayam",
//   "Kozhikode",
//   "Kumbakonam",
//   "Kurnool",
//   "Latur",
//   "Loni",
//   "Madhubani",
//   "Malda",
//   "Mangalore",
//   "Margoa",
//   "Mathura",
//   "Medinipur",
//   "Mehsana",
//   "Mirzapur",
//   "Morena",
//   "Muzaffarpur",
//   "Nadiad",
//   "Nagaon",
//   "Nagercoil",
//   "Nagapattinam",
//   "Nagpur",
//   "Nainital",
//   "Namakkal",
//   "Nanded",
//   "Nandurbar",
//   "Narasaraopet",
//   "Navsari",
//   "Nellore",
//   "New Delhi",
//   "Neyveli",
//   "Nizamabad",
//   "Noida",
//   "Nokha",
//   "Ongole",
//   "Palakkad",
//   "Palanpur",
//   "Pali",
//   "Panipat",
//   "Parbhani",
//   "Pathankot",
//   "Patiala",
//   "Phagwara",
//   "Pondicherry",
//   "Pudukkottai",
//   "Raebareli",
//   "Raichur",
//   "Rajahmundry",
//   "Rajapalayam",
//   "Rajgarh",
//   "Rajkot",
//   "Raniganj",
//   "Rajsamand",
//   "Ramagundam",
//   "Rampur",
//   "Ranchi",
//   "Ratlam",
//   "Ratnagiri",
//   "Rewa",
//   "Rewari",
//   "Rohtak",
//   "Rourkela",
//   "Sagar",
//   "Saharanpur",
//   "Salem",
//   "Sambalpur",
//   "Sangli",
//   "Satara",
//   "Satna",
//   "Sehore",
//   "Shahjahanpur",
//   "Shimla",
//   "Shillong",
//   "Shimoga",
//   "Sikar",
//   "Silchar",
//   "Siliguri",
//   "Sindhudurg",
//   "Singrauli",
//   "Sirsa",
//   "Sitapur",
//   "Solan",
//   "Sonipat",
//   "South Dumdum",
//   "Sri Ganganagar",
//   "Srikakulam",
//   "Srinagar",
//   "Surat",
//   "Tadepalligudem",
//   "Tandur",
//   "Tenali",
//   "Tenkasi",
//   "Tezpur",
//   "Thanjavur",
//   "Thiruvalla",
//   "Thiruvananthapuram",
//   "Thoothukudi",
//   "Thrissur",
//   "Tiruchirappalli",
//   "Tirunelveli",
//   "Tirupati",
//   "Tiruppur",
//   "Tiruvannamalai",
//   "Tonk",
//   "Tumkur",
//   "Udaipur",
//   "Udgir",
//   "Ujjain",
//   "Ulhasnagar",
//   "Ullal",
//   "Umarkhed",
//   "Unnao",
//   "Vadodara",
//   "Valsad",
//   "Vapi",
//   "Varanasi",
//   "Vellore",
//   "Veraval",
//   "Vidisha",
//   "Vijayawada",
//   "Viluppuram",
//   "Virar",
//   "Virudhunagar",
//   "Visakhapatnam",
//   "Vizianagaram",
//   "Warangal",
//   "West Bengal",
//   "Wardha",
//   "Wayanad",
//   "Yavatmal",
//   "Yelahanka",
//   "Yemmiganur",
//   "Yerraguntla",
// ];

// const States = [
//   "Andhra Pradesh",
//   "Arunachal Pradesh",
//   "Assam",
//   "Bihar",
//   "Chhattisgarh",
//   "Goa",
//   "Gujarat",
//   "Haryana",
//   "Himachal Pradesh",
//   "Jharkhand",
//   "Karnataka",
//   "Kerala",
//   "Madhya Pradesh",
//   "Maharashtra",
//   "Manipur",
//   "Meghalaya",
//   "Mizoram",
//   "Nagaland",
//   "Odisha",
//   "Punjab",
//   "Rajasthan",
//   "Sikkim",
//   "Tamil Nadu",
//   "Telangana",
//   "Tripura",
//   "Uttar Pradesh",
//   "Uttarakhand",
//   "West Bengal",
//   "Andaman and Nicobar Islands",
//   "Chandigarh",
//   "Dadra and Nagar Haveli and Daman and Diu",
//   "Lakshadweep",
//   "Delhi",
//   "Puducherry",
//   "Ladakh",
//   "Jammu and Kashmir",
// ];



const StatesAndCities = {
    "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Tirupati", "Kakinada", "Rajahmundry", "Anantapur", "Kadapa", "Kurnool"],
    "Arunachal Pradesh": ["Itanagar", "Naharlagun", "Tawang", "Ziro", "Bomdila", "Pasighat"],
    "Assam": ["Guwahati", "Dibrugarh", "Silchar", "Jorhat", "Tezpur", "Nagaon", "Tinsukia", "Bongaigaon"],
    "Bihar": ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Purnia", "Darbhanga", "Begusarai", "Katihar", "Arrah", "Sasaram"],
    "Chhattisgarh": ["Raipur", "Bhilai", "Bilaspur", "Korba", "Durg", "Rajnandgaon", "Jagdalpur", "Ambikapur"],
    "Goa": ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda"],
    "Gujarat": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar", "Gandhinagar", "Junagadh", "Anand", "Morbi"],
    "Haryana": ["Chandigarh", "Faridabad", "Gurgaon", "Ambala", "Hisar", "Panipat", "Rohtak", "Yamunanagar"],
    "Himachal Pradesh": ["Shimla", "Manali", "Dharamshala", "Kullu", "Solan", "Mandi"],
    "Jharkhand": ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Hazaribagh", "Deoghar", "Giridih"],
    "Karnataka": ["Bangalore", "Mysore", "Mangalore", "Hubli", "Belgaum", "Gulbarga", "Davanagere", "Bellary", "Shimoga"],
    "Kerala": ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam", "Palakkad", "Alappuzha"],
    "Madhya Pradesh": ["Bhopal", "Indore", "Jabalpur", "Gwalior", "Ujjain", "Sagar", "Satna", "Dewas", "Rewa"],
    "Maharashtra": ["Mumbai", "Pune", "Nagpur", "Nashik", "Thane", "Aurangabad", "Solapur", "Amravati", "Kolhapur", "Sangli"],
    "Manipur": ["Imphal", "Thoubal", "Bishnupur", "Churachandpur", "Senapati"],
    "Meghalaya": ["Shillong", "Tura", "Nongpoh", "Jowai"],
    "Mizoram": ["Aizawl", "Lunglei", "Saiha", "Champhai"],
    "Nagaland": ["Kohima", "Dimapur", "Mokokchung", "Tuensang"],
    "Odisha": ["Bhubaneswar", "Cuttack", "Rourkela", "Sambalpur", "Berhampur", "Puri", "Balasore"],
    "Punjab": ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Hoshiarpur"],
    "Rajasthan": ["Jaipur", "Jodhpur", "Kota", "Udaipur", "Ajmer", "Bikaner", "Bhilwara", "Alwar"],
    "Sikkim": ["Gangtok", "Namchi", "Mangan", "Rangpo"],
    "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Tirunelveli", "Erode", "Thoothukudi"],
    "Telangana": ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Ramagundam"],
    "Tripura": ["Agartala", "Udaipur", "Dharmanagar", "Kailasahar"],
    "Uttar Pradesh": ["Lucknow", "Kanpur", "Varanasi", "Agra", "Meerut", "Allahabad", "Ghaziabad", "Bareilly"],
    "Uttarakhand": ["Dehradun", "Haridwar", "Rishikesh", "Haldwani", "Nainital"],
    "West Bengal": ["Kolkata", "Asansol", "Siliguri", "Durgapur", "Howrah", "Kharagpur", "Bardhaman"]
}
  
  
locationController.get("/state/list", (req, res) =>
  sendResponse(res, 200, "Success", {
    success: true,
    message: "States retrieve successfully!",
    States: StatesAndCities,
  })
);

locationController.get("/cities/list", (req, res) =>
  sendResponse(res, 200, "Success", {
    success: true,
    message: "Cities retrieve successfully!",
    Cities: City,
  })
);

module.exports = locationController;
