const express = require("express");
const router = express.Router();
const userController = require("./controller/userController");
const adminController = require("./controller/adminController");
const supportController = require("./controller/supportController");
const notificationController = require("./controller/notificationController");
const roleController = require("./controller/roleController");
const permissionController = require("./controller/permissionController");
const ticketCategoryController = require("./controller/ticketCategoryController");
const ticketController = require("./controller/ticketController");
const chatController = require("./controller/chatController");
const notifyController = require("./controller/notifyController");
const loanController = require("./controller/loanController");
const branchController = require("./controller/branchController");
const documentController = require("./controller/documentController");
const loanApplicationController = require("./controller/loanApplicationController");
const loanPurposeController = require("./controller/loanPurposeController");
const paydayLoanController = require("./controller/paydayLoanController");
const systemConfigrationController = require("./controller/systemConfigrationController");
const paydayLoanApplicationController = require("./controller/paydayLoanApplicationController");
const notificationConfigrationController = require("./controller/notificationConfigrationController");
const notificationEventController = require("./controller/notificationEventController");
const auth = require("./middleware/auth");

router.use("/user", userController);
router.use("/admin", adminController);

router.use(auth);
router.use("/support", supportController);
router.use("/notification", notificationController);
router.use("/role", roleController);
router.use("/permission", permissionController);
router.use("/ticket-category", ticketCategoryController);
router.use("/ticket", ticketController);
router.use("/chat", chatController);
router.use("/notify", notifyController);
router.use("/loan", loanController);
router.use("/branch", branchController);
router.use("/document", documentController);
router.use("/loan-application", loanApplicationController);
router.use("/loan-purpose", loanPurposeController);
router.use("/payday-loan", paydayLoanController);
router.use("/payday-loan-application", paydayLoanApplicationController);
router.use("/system-configration", systemConfigrationController);
router.use("/notification-configration", notificationConfigrationController);
router.use("/notification-event", notificationEventController);

module.exports = router;
